import './globals.css'
import type { Metadata } from 'next'
import { GlobalContextProvider } from '@/app/Context/GlobalContext';
import Navbar from '@/components/Navbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="relative">
        <GlobalContextProvider>  
          <Navbar/>
          {children}
        </GlobalContextProvider>
      </body>
    </html>
  )
}
